# Generated by Django 4.2.5 on 2023-09-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploaded_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
